export const MOOD_OPTIONS = [
  { emoji: '😊', label: '开心' },
  { emoji: '☀️', label: '晴天' },
  { emoji: '😌', label: '平静' },
  { emoji: '☕', label: '咖啡' },
  { emoji: '🍜', label: '吃饭' },
  { emoji: '😴', label: '疲惫' },
  { emoji: '💻', label: '加班' },
  { emoji: '🏠', label: '宅家' },
  { emoji: '🌧️', label: '下雨' },
  { emoji: '🤔', label: '思考' },
  { emoji: '🥰', label: '幸福' },
  { emoji: '😐', label: '一般' },
  { emoji: '🚗', label: '通勤' },
  { emoji: '✈️', label: '出差' },
  { emoji: '📚', label: '学习' },
  { emoji: '🏃', label: '运动' },
  { emoji: '🌙', label: '熬夜' },
  { emoji: '😢', label: '难过' },
  { emoji: '😤', label: '生气' },
  { emoji: '🤒', label: '生病' },
] as const;
